### ISSUE TITLE
ledControl inserted in configuration is incorrect

### ISSUE THREAD

**Issue by benoittgt** [kiibohd/KiiConf#82]
Led control generate from https://input.club/configurator-ergodox/ are incorrect. It gave 3 parameter when the method wants 2.

```
Name = "MDErgo1";
Layout = "Default";
Base = "Blank";
Version = "0.1";
Author = "HaaTa (Jacob Alexander) 2015";
KLL = "0.3c";
Date = "2015-09-12";
Generator = "KIICONF 0.2";

U"ESC" : U"F11";
U"5" : U"F5";
U"4" : U"F4";
U"3" : U"F3";
U"2" : U"F2";
U"1" : U"F1";
U"EQUALS" : flashMode();
U"FUNCTION1" : U"PAGEUP";
U"FUNCTION2" : U"LSHIFT";
U"FUNCTION6" : U"F12";
U"6" : U"F6";
U"7" : U"F7";
U"8" : U"F8";
U"9" : U"F9";
U"0" : U"F10";
U"MINUS" : flashMode();
U"Y" : ledControl( 4, 15, 0 );
U"RBRACE" : CONS"VOLUMEUP";
U"H" : ledControl( 3, 15, 0 );
U"QUOTE" : CONS"VOLUMEDOWN";
U"N" : ledControl( 5, 0, 0 );
U"RSHIFT" : CONS"MUTE";
U"RGUI" : U"DELETE";
```

Give 
```
-- Build files have been written to: /Users/bti/code/controller/Keyboards/darwin16.miami_ergodox_r.gcc.make
[  3%] Generating KLL Layout
kll BETA 0.5c.54d839fa7a8dcd4352da10288512036a54e247dc - 2017-10-21 16:11:42 +0200
ERROR: incorrect number of arguments for ledControl(3,15,0). Expected 2 Got 3
	ledControl <= LED_control_capability(mode:1,amount:1);
Traceback (most recent call last):
  File "../../kll/kll", line 159, in <module>
    control.process()
  File "/Users/bti/code/controller/kll/common/stage.py", line 123, in process
    stage.process()
  File "/Users/bti/code/controller/kll/common/stage.py", line 2827, in process
    self.emitter.process()
  File "/Users/bti/code/controller/kll/emitters/kiibohd/kiibohd.py", line 671, in process
    self.fill_dict['ResultMacros'] += "{0}, ".format(self.result_combo_conversion(combo))
  File "/Users/bti/code/controller/kll/emitters/kiibohd/kiibohd.py", line 252, in result_combo_conversion
    if identifier.total_arg_bytes(self.capabilities.data) > 0:
  File "/Users/bti/code/controller/kll/common/id.py", line 560, in total_arg_bytes
    raise AssertionError("Invalid arguments")
AssertionError: Invalid arguments
make[2]: *** [generatedKeymap.h] Error 1
make[1]: *** [CMakeFiles/kiibohd.dir/all] Error 2
make: *** [all] Error 2
Error in make. Exiting...
```

**Comment by jbondeson** [comment]
This is a mismatch between the latest `controller` and `kll` versions and the live versions on the websites. This was fixed a while ago on the `feature/restructure` branch. I just merged it through and am in the process of deploying now.
